export const SKILLS = [
    "Plumber",
    "Electrician",
    "Carpenter",
    "Painter",
    "Mason",
    "Driver",
    "Mechanic",
    "Tailor",
    "Domestic Worker",
    "Cook",
    "Caregiver",
    "Babysitter",
    "Farmer",
    "Livestock Helper",
    "Shop Assistant",
    "Cleaner",
    "Security Guard",
    "Delivery Worker",
    "Construction Laborer",
];
